; HEADER_BLOCK_START
; generated by OrcaSlicer 2.2.0 on 2026-04-15 at 19:03:45
; total layer number: 25
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 5.00
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 96x96 1472
; iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAEFUlEQVR4Ae2bW0sVURTH57WraOoJzY
; 4lBD34EBTkgxEVhBFZWFFWJkI3oRCLLqSkVGpEQfXUkx/lfJTzUaaWMMNynL3PXPbMXnuf/w/2iy+e
; s35r9trrzNpBAAAAAAAAAAAAAAAAAPtOjV0MQP30Xr+6Nvb3Zxit5sZKmxb9nRbEVAgP/onfW+Ho9/
; WQy0iKgRSDUEB3Av9rMxz+sBQOPLwTNhYexGto6Xk4svomPP7l444clZTB+fvbkJKDXVn/P/iDC7Nh
; /+zMHgGqRVJoqZ4WkjL0erFF/+fQxLl5iGFEWU+Lsp4CH62sAtLW8LtXHaV09RaWzPpk8MsKSFvRFt
; aprni/hfHgN799irecqgXopKjE0NYV+AJlVLLQpgW+TgGq1fy6EksIfEBVaKUKaDydiwXQlhS4TJ6s
; lySgubnq9lOQzPqjiwuZgy9BwLGV5VgAHV8Dl6DipTpeuiKAEubkny23tqEsx0uXBDi1DRUptNIF0H
; JiGypaaF0QMPrjc9ykBdIwnfUSBfBiLKo71v2O45MAvg2JKcZHbt/Yjj7UyPp748GXJkBcMe65NNlV
; AsT1BCSAZ4XvAsT1BCSAZ8XQ8gvvBdCTLmYbIgE8K6rYhqQJ4MWYTn+BTSIBfBsyeQSl1XfzWluagK
; gnsP4URAJ4Vpjchnqnp/Y0PQfOjK/1Tl1p2RQgpifgAnhWVBF4HZVJUQgQ0xNwATwr8v7kXCb4OkpL
; 0QgQ0RNwATwrihbj/eOn14KKyfW0aAQMv31pvydICijaE5jM+iIopWgEiOgJkgKK9AQ9ly+InDggKQ
; OzM22dAP59AxskBeTpCWxnfVZ0AnhTZuUpSBPAs0LVE7gSfKJveqql236idx8Hz5+VIaBTMa6j0JpG
; lfV8yECUgLSewKWsT5L2vZLvPkQJSPYEVj6cQRrPHrc6DRmIEiCmUzRA1tet4gQ4P1EW5BsyECdARK
; dYkCJDBuIE8KOaS+PdRYcMRAqw3inmoOw0n7WDhk4AL8bRVSCJ21HWyyIiBag6xbgYb6wqrwHZvp+V
; 97KISAGETkDjyVz862KnS3ORmDruZ5me5nNCQNri936zXDE1IaWKGVarAnTFuJMA1ari3m/ZyyJiBR
; CmBaStMvd+TVwWES1g4NHddtUCdFuYrq6UOV46I4CwIUAnhYsxPTYPATlXVYEXJSCtJ4CAmoEAy0CA
; ZZI9QTcIEPe6tVsEUOBFDhnwnsBXAeKHDHwW4MRojY8CnBqtiXoCXwQ4OdfkgwCXB8p2irHLApwOPk
; E9gasCXJxhTcU1Ac5nfZL+e7fargiQelnEGLVeMc0hwLusz0NdUhD8HFQhJS3w3hTaujg8ObFtQgCy
; 3iBZnxbvjpeSSZOCrAcAAAAAAAAAAAAAAADb/AOlOGw0M09jcAAAAABJRU5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 4780
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAANyElEQVR4Ae3dXatc1RnA8bmtWiWS+p
; IYNRUKXuRCsKAXSqmCBKQKLUJNSyVCtUIlqFRFpQkVtUgF7ZVX+Sj5KPkop66UI5M4c2bvmfX67N8P
; Fr3JVc/xv9d6ztozqxUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAFfzsV0/85tTLL11N/7sC6FUK1RPff3O0vh774tObZ95/54aIAd1IYbozVtvWesSEDKhm065q
; 35VCJmJAEWmXlCtWJ0XsgTf+eF3EgL3k3FXtG7HjI+XPn/31GyuATabG6vy3Xx49/vW1qhFzpAR+NH
; WwnmL1wOXXj344yh09ePnSrXXmyttH5z774OjRzz+pFjFzMVigOUfAsx9fOTr9+u9vrfVgbVspYmnV
; 3o2Zi0FAc3ZV67GaGqxN6+yH7zaJ2PpcTMhgIHN2VY/9+5+3joDrsTokWD1FzJESOjdnsH7nrqpUsD
; at9bmYIyUsTPqPb+5gfVusagSrt7mYV5Cgkn0H6z0Gq8e5mJBBJnN2VQ+9c3lSrHoL1klHypoROw6Z
; iMFMc3ZV5659NDlUowTrpIi5agEdmfoe4K7BerRgbVut52JeQWKR0i/+1P9gpgzWlxKsTctVCygo13
; UFwdq+1q9anP/uq6ohc6QkjFKDdcGatly1gAlKXFcQrDyr5VWLFfSmxmBdsPKuWlctDPHpxpxd1aGD
; dcGqF7GcIUvzrhW0VnuwLljt1qERW0FLOd8DFKwx15y5mGMhTbQcrAtWv+uRH37WuwbwK6jpkA/YE6
; zY66G3/nL0y/+efBfMdQeqyPEBe4IVP1iPffmZ4Ttt9TRYF6y+g3X2H383fKeN3B+wJ1jxg5XeWth1
; LDR8J7tRdlWC1V+wHvn0PcdC6mnxHqBgxQlWWo6FFNfrdQXBGi9Yu4bv6XdtBftq/R6gYMUK1q5joV
; 0We+nlPUDBihWsKcN3d7KYZcTBumCNEyx3sshmpOsKgjVmsNzJ4mCjD9YFa5xgpfX4f/514u+YO1ls
; 1fN7gIIVM1juZDHbCO8BClbMYLmTxSzRBuuCNV6wDN/ZabT3AAUrbrDcyeJES9pVCVb/wXIni61GfQ
; 9QsGIHy7GQ28wZrJ+79tFQIRKs8YNl+M6PIrwHKFjxg+VO1sJFeg9QsOIHa9fw3TdEB7bUwbpgjRss
; x8KFWvJgXbDGDpbh+4JEfg9QsJYRLHeyFiL6e4CCtYxg+ZKK4JbyHqBgLSdYXogOymBdsCIGy/A9mC
; W+ByhYywqWO1lBGKwL1hKC5U5WELuePMe7qjPv/W2omAiWYM09FnohegBT/uzrCChYEYLlTlYAU548
; giVYEYLlSyoCmPLkifppC4K1rGC5kxXAlIFkWiOFRLAEy52soKY+eQzdBStCsNzJGtzUJ49joWBFCZ
; Y7WQOb8+QxfBesCMHyQvTA5jx5HAsFK0KwpoxA3Mnq1JwnT3rZeaSgCJZguZMVzNyBZPo3I0VFsATL
; naxA5j55DN8FK0KwDN8Htc+TZ6SoCJZg7Tt8dyzs0D4DScN3wYoQrCkjkBV92efJ41goWFGCZfg+mH
; 2fPO5kCVaEYLmTNZh9B5KOhYIVIVhTRiDuZHXkkCfPSHERrHgrV7AcCwdyyJMn/ZuRApNznXrl4s30
; /9/dT124euriizdG+g9dsOaPQFb04ZAnzxKH78eh2kXIxgqWO1mDOOmH6E7WfrHaRsT6DZYvqRjEoQ
; PJpQzf77rw5NVVASLWR7AcCwdx6JMn+rHw0F3Vvu597tnrI8UjQrAM3weQ48kT9U7WfS8839UxwG6s
; bLDcyRpAjidPtF1Wq13VPpYcsdzBmjICcSersVxPnpGCFCVW2ywlYiWClR6+joUdy/XkSf9mpDBtWq
; UG671Ic7FIISsRrCkjkBXtTP0hRj4WRthV7Wvk3VipYLmT1bGpP8SHr7wV8lh4zzNP2+LfYZSIlQqW
; O1kdy/nkGelO1pJ3VfvqLWKlgjXlWGj43kjOJ88oX1IhVvm03I2VDJY7WZ3K/eTp+U6WUNVRK2Ilg+
; VLKjqV+8nT6/BdrNoqEbGSwUpr11/GDd8bmPtDHPFOVvTrCiNLVy1Ov/bqzR6D5UsqOlTiyZP+TQ+h
; sqsa09TdWOlgpeVY2Jl9foi7bgP3cCwUq1g2RaxGsNzJ6kypJ0+r4btQLcf9v7t4o3Swdv5l/ItP/b
; 7VVOrJ0+JOllgtT+lgpeWF6I4Ue/JUvpNlsL5M979Sdpe1a/xh+F7ZIT/MXT/I9G/sqiit1c7qeJ3/
; 9kvD91oO+YG2vpPV2wfs0UaLXdX6SSLNa1fUccgPttWdLLsq1t332+eu54rVrofw+q7q7MdXfvydXF
; FH6W1z7uG7WLHJob/H6eE75wh451/BV9SR4wdd41iYQmWwzja/+PNrN0sfAe/cVQlWAzm20Tv/inLg
; nSy7KnbZ91g4Z1eV/v2239EVdeQIVsk7WXZVTFViV5XWtl2VYDWQI1i7joXp6WRXRWlT72TtesBOOQ
; IKViM5gjVla33SdlqsyCXXrmruKGNFHbmCleNOllBxqFpHQMFqJFewpnxCo1hR2qbh+9TB+txdlWA1
; kCtYU34xtg3fDdbJqdauSrAayBmsuXey7Koo4YE3L92cs6s6NFaCVVHOYKU1dcvtPUBKOPXyS1enhu
; r4PcBDYyVYFeUO1q7h+8Pv/tWuiiLmxCrHrkqwGsgdrCkvRK8go/QBeumTP0sP1gWrA7mDNWX47hMa
; yaXlrkqwGigRLN+aSw1zdlXp97JUrASrohLB8q25lNTLrkqwGigRrLR8PRIlnHn/nRtTQjXnPUDBGk
; ipYO0avqdfvBVMNGdXtekD9gQriFLBSsuxkBymxqr2rkqwGigZLMN3DjV1sN5iVyVYDZQMljtZ7KvH
; wbpgdaBksNJyJ4u55uyqeoiVYFVUOliOhUzV6j1AwRpI6WAZvjPFCIN1wepAjWC5k8U2c94DbD1YF6
; wO5PzW3H2H7+5kLdNog3XB6kSNXdauX8gVizJnV5X728MFa3CHfGturuF72mX5i2F8c3ZV6RNqez0C
; ClZjrY+F6ys9fVPA0i93WkIWQ/qL8NRdVe9HQMFqrMaxcM7nbG8LmYiNJ/1RZerPuOfBumB1ZOq35t
; baZc2JWHpyi1ifRr+uIFgdq7HLyh2sXUdKVybamTNYT78bIwVKsDpQY/j+8A/r7IfvHp377IOjx7++
; ViVgxxFzpKwj0nUFwepYjTtZD775p6MHL1/6yTpz5e1bEXv080+Ozn/31dET339TZTlS5tXrB+wJVl
; CtgrVtpYi12I0dHylFbJreP2BPsIIqfSycG6xNq9WR0lWLzZYyWBesTvUerJOOlDUjdhyyJUcswnuA
; gjW4EYN1UsRa7Maiz8WWOFgXrE6VHL7XDFavc7HRr1qM+AF7ghVc5GD1NBcb6Ug58gfsCVZwpYbvvQ
; brpCNlumpRK2LHIestYgbrgtW1UsfCkYK1bS1pLhblA/YEawEEq/+Irc/FcofMrkqwhlLiheiowdq0
; Rp6LLek9QMEKRLDyrvW5WI9HStcVBGtoglVn9fAK0lLfAxSsQHIP3wVr+mpxpJwSq6UO1gVrEILVz2
; r1CpJdlWANI+edLMEqF7FSIbOrEqyh5DwWCla9lSNidlWCNSTBirGmzsUcAQVraLnuZAlWf+vOT3td
; 2nuAghWUYC1jnb70h6FiIVhsJFjLWIIlWCHkGL4LVv9LsAQrDMGKvwRLsMI49E6WYPW/BEuwQhGs2E
; uwBCsUwYq9BEuwQjnkTpZg9b8ES7DCEay4S7AEKxzBirsES7DC2fdOlmD1vwRLsEISrJhLsAQrpH3u
; ZAlW/0uw5q27Ljx5dcUYBCveEqxp69QrF2+uGItgxVuCtXvd98LzN1aMZ+7wXbD6X4K1fdlVBSBYsZ
; ZgiVVoc4bvgtX/EqyfhspgPZA5x0LB6n8J1u2xWhGPYMVZgvX/ZVcV2NQXogWr/7X0YNlVLYRgxVhL
; DpZYLYhgxVhLDJZQLdCU4btg9b+WFiyxWjDBGn8tKVgG6wu3606WYPW/lhAsuypu2XUsFKz+V/RgeQ
; +Q2wjW2CtqsOyq2OikO1mC1f+KGCyx4kSCNe6KFCzvATKJYI27ogTLrorJtg3fBav/FSFYdlXMJlhj
; rpGDZVfF3jbdyRKs/teowRIrDiZY463RgiVUZCNY462RgiVWZHXnnSzB6n+NEiyDdYoQrLFW78Gyq6
; IowRpr9Rws7wFS3PqdLMHqf/UYLLsqqhKscVZvwRIrqju+kyVY/a+egmWwTjOCNcbqIVh2VTQnWGOs
; 1sG655mnr6+gtXQnS7D6X62CZVdFdwSr/9UiWGJFl+597tnrI/3Hu8RVM1g+YI/hnLr44o2R/oOOvm
; oFy66KMO5+6sJVIWuzagTLrorwRKzOKhksuyoWTcTGCZZYwRZpuH/6tVdvjhSKqMESKtiD3Vj9YIkV
; ZCRi5YJlsA4VLD1ihwbLrgo6sJSQHRIsH7AHHYsYsX2CZVcFgxo9YnODJVYQ0CjvUU4NlvcAYWF63I
; 1NCZZdFXBL64jtCpZdFXCimhHbFiy7KuAgaS6WO2SbgiVWQBGH7sbWgyVUQHVzInYcLLECurIpYilY
; BusAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKz5H2yHSP
; atrP0lAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; support material extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=tolerance_test.stl_id_0_copy_0 CENTER=110,110 POLYGON=[[104.227,110],[107.113,105],[112.887,105],[115.773,110],[112.887,115],[107.113,115],[104.227,110]]
M73 P0 R1
;TYPE:Custom
M220 S100 ;Reset feed rate 
M221 S100 ;Reset flow rate 

M140 S60 ;Set final bed temp
G28 ;Home 
G92 E0 ;Reset extruder 
G1 Z2.0 F3000 ;Move Z Axis up 
G1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position 
M190 S60 ;Wait for bed temp to stabilize
M109 S220 ;Wait for nozzle temp to stabilize
G1 X10.1 Y145.0 Z0.28 F1500.0 E15 ;Draw the first line 
G1 X10.4 Y145.0 Z0.28 F5000.0 ;Move to side a little 
M73 P5 R1
M73 P5 R1
G1 X10.4 Y20 Z0.28 F1500.0 E30 ;Draw the second line 
G92 E0 ;Reset extruder 
G1 E-1.0000 F1800 ;Retract a bit 
M73 P10 R1
M73 P10 R1
G1 Z2.0 F3000 ;Move Z Axis up 
G1 E0.0000 F1800
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
M106 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 E-.8 F1800
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=1000 ACCEL_TO_DECEL=500
SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=7
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z.6 F24000
G1 X115.477 Y109.906
G1 Z.6
M73 P11 R1
M73 P11 R1
G1 Z.2
G1 E.8 F2400
;TYPE:Outer wall
;WIDTH:0.41974
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
M73 P12 R1
M73 P12 R1
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P13 R1
M73 P13 R1
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.56 F1800
M73 P14 R1
;WIPE_START
M73 P14 R1
G1 F3000
G1 X115.522 Y110.016 E-.03808
G1 X115.101 Y110.744 E-.20192
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
M106 S255
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.4
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=5000 ACCEL_TO_DECEL=2500
M140 S60 ; set bed temperature
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z.8 F24000
G1 X115.477 Y109.906
G1 Z.4
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P15 R1
M73 P15 R1
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
M73 P16 R1
M73 P16 R1
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
M73 P17 R1
M73 P17 R1
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
;WIPE_START
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.6
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z1 F24000
G1 X115.477 Y109.906
M73 P18 R1
M73 P18 R1
G1 Z.6
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
M73 P19 R1
M73 P19 R1
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P20 R1
M73 P20 R1
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
M73 P21 R1
;WIPE_START
M73 P21 R1
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.8
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z1.2 F24000
G1 X115.477 Y109.906
G1 Z.8
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P22 R1
M73 P22 R1
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
M73 P23 R1
M73 P23 R1
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
M73 P24 R1
M73 P24 R1
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
;WIPE_START
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z1.4 F24000
G1 X115.477 Y109.906
G1 Z1
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P25 R1
M73 P25 R1
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
M73 P26 R1
M73 P26 R1
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P27 R1
M73 P27 R1
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
M73 P28 R1
;WIPE_START
M73 P28 R1
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:1.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.2
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z1.6 F24000
G1 X115.477 Y109.906
G1 Z1.2
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
M73 P29 R1
M73 P29 R1
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P30 R1
M73 P30 R1
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
M73 P31 R1
M73 P31 R1
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
;WIPE_START
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.4
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z1.8 F24000
G1 X115.477 Y109.906
G1 Z1.4
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P32 R1
M73 P32 R1
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
M73 P33 R1
M73 P33 R1
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
M73 P34 R1
M73 P34 R1
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
M73 P35 R1
;WIPE_START
M73 P35 R1
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:1.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.6
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z2 F24000
G1 X115.477 Y109.906
G1 Z1.6
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
M73 P36 R1
M73 P36 R1
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P37 R1
M73 P37 R1
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
M73 P38 R1
;WIPE_START
M73 P38 R1
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:1.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.8
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z2.2 F24000
G1 X115.477 Y109.906
G1 Z1.8
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P39 R1
M73 P39 R1
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
M73 P40 R1
M73 P40 R1
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
M73 P41 R1
M73 P41 R1
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
;WIPE_START
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z2.4 F24000
G1 X115.477 Y109.906
G1 Z2
G1 E.8 F2400
M73 P42 R1
M73 P42 R1
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P42 R0
M73 P42 R0
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
M73 P43 R0
M73 P43 R0
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P44 R0
M73 P44 R0
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
M73 P45 R0
;WIPE_START
M73 P45 R0
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:2.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2.2
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z2.6 F24000
G1 X115.477 Y109.906
G1 Z2.2
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P46 R0
M73 P46 R0
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
M73 P47 R0
M73 P47 R0
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
M73 P48 R0
M73 P48 R0
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
;WIPE_START
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:2.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2.4
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z2.8 F24000
G1 X115.477 Y109.906
G1 Z2.4
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P49 R0
M73 P49 R0
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
M73 P50 R0
M73 P50 R0
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P51 R0
M73 P51 R0
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
M73 P52 R0
;WIPE_START
M73 P52 R0
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:2.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2.6
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z3 F24000
G1 X115.477 Y109.906
G1 Z2.6
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
M73 P53 R0
M73 P53 R0
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P54 R0
M73 P54 R0
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
M73 P55 R0
;WIPE_START
M73 P55 R0
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:2.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2.8
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z3.2 F24000
G1 X115.477 Y109.906
G1 Z2.8
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P56 R0
M73 P56 R0
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
M73 P57 R0
M73 P57 R0
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
M73 P58 R0
M73 P58 R0
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
;WIPE_START
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:3
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z3.4 F24000
G1 X115.477 Y109.906
M73 P59 R0
M73 P59 R0
G1 Z3
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
M73 P60 R0
M73 P60 R0
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P61 R0
M73 P61 R0
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
M73 P62 R0
;WIPE_START
M73 P62 R0
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:3.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3.2
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z3.6 F24000
G1 X115.477 Y109.906
G1 Z3.2
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P63 R0
M73 P63 R0
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
M73 P64 R0
M73 P64 R0
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
M73 P65 R0
M73 P65 R0
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
;WIPE_START
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:3.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3.4
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z3.8 F24000
G1 X115.477 Y109.906
G1 Z3.4
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P66 R0
M73 P66 R0
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
M73 P67 R0
M73 P67 R0
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P68 R0
M73 P68 R0
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
M73 P69 R0
;WIPE_START
M73 P69 R0
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:3.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3.6
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z4 F24000
G1 X115.477 Y109.906
G1 Z3.6
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
M73 P70 R0
M73 P70 R0
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
M73 P71 R0
M73 P71 R0
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
M73 P72 R0
M73 P72 R0
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
;WIPE_START
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:3.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3.8
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z4.2 F24000
G1 X115.477 Y109.906
G1 Z3.8
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P73 R0
M73 P73 R0
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
M73 P74 R0
M73 P74 R0
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
M73 P75 R0
M73 P75 R0
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
M73 P76 R0
;WIPE_START
M73 P76 R0
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z4.4 F24000
G1 X115.477 Y109.906
G1 Z4
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
M73 P77 R0
M73 P77 R0
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P78 R0
M73 P78 R0
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
M73 P79 R0
;WIPE_START
M73 P79 R0
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:4.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4.2
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z4.6 F24000
G1 X115.477 Y109.906
G1 Z4.2
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P80 R0
M73 P80 R0
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
M73 P81 R0
M73 P81 R0
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
M73 P82 R0
M73 P82 R0
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
;WIPE_START
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:4.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4.4
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z4.8 F24000
G1 X115.477 Y109.906
G1 Z4.4
G1 E.8 F2400
M73 P83 R0
M73 P83 R0
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
M73 P84 R0
M73 P84 R0
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P85 R0
M73 P85 R0
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
M73 P86 R0
;WIPE_START
M73 P86 R0
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:4.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4.6
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z5 F24000
G1 X115.477 Y109.906
G1 Z4.6
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P87 R0
M73 P87 R0
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
M73 P88 R0
M73 P88 R0
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
M73 P89 R0
M73 P89 R0
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
;WIPE_START
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:4.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4.8
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z5.2 F24000
G1 X115.477 Y109.906
G1 Z4.8
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
M73 P90 R0
M73 P90 R0
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
M73 P91 R0
M73 P91 R0
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P92 R0
M73 P92 R0
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
M73 P93 R0
;WIPE_START
M73 P93 R0
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
;LAYER_CHANGE
;Z:5
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;5
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object tolerance_test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=tolerance_test.stl_id_0_copy_0
G1 Z5.4 F24000
G1 X115.477 Y109.906
G1 Z5
G1 E.8 F2400
G1 F600
G1 X115.522 Y110.016 E.00365
G1 X112.82 Y114.696 E.16594
G1 X112.747 Y114.79 E.00365
G1 X107.343 Y114.79 E.16594
G1 X107.225 Y114.774 E.00365
M73 P94 R0
M73 P94 R0
G1 X104.523 Y110.094 E.16594
G1 X104.478 Y109.984 E.00365
G1 X107.18 Y105.304 E.16594
G1 X107.253 Y105.21 E.00365
M73 P95 R0
M73 P95 R0
G1 X112.657 Y105.21 E.16594
G1 X112.775 Y105.226 E.00365
M73 P96 R0
M73 P96 R0
G1 X115.457 Y109.871 E.16471
; stop printing object tolerance_test.stl id:0 copy 0
G1 E-.61159 F1800
;WIPE_START
G1 F9553.633
G1 X115.522 Y110.016 E-.0299
G1 X115.101 Y110.744 E-.15851
;WIPE_END
EXCLUDE_OBJECT_END NAME=tolerance_test.stl_id_0_copy_0
M106 S0
;TYPE:Custom
; filament end gcode 
G91 ;Relative positioning 
G1 E-2 F2700 ;Retract a bit 
G1 E-2 Z0.2 F2400 ;Retract and raise Z 
G1 X5 Y5 F3000 ;Wipe out 
G1 Z3 ;Raise Z more 
G90 ;Absolute positioning 
G1 X2 Y218 F3000 ;Present print 
M106 S0 ;Turn-off fan 
M104 S0 ;Turn-off hotend 
M140 S0 ;Turn-off bed 
M84 X Y E ;Disable all steppers but Z
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 55.41
; filament used [cm3] = 0.13
; filament used [g] = 0.17
; filament cost = 0.00
; total filament used [g] = 0.17
; total filament cost = 0.00
; total layers count = 25
; estimated printing time (normal mode) = 1m 42s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 70
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 4
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 65
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = no_brim
; brim_width = 5
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = M600
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 80
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 60
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 5000
; default_filament_colour = ""
; default_filament_profile = "Creality Generic PLA"
; default_jerk = 7
; default_print_profile = 0.20mm Standard @Creality CR10SE 0.4
; deretraction_speed = 40
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 1
; different_settings_to_system = enable_support;raft_first_layer_density;sparse_infill_density;support_style;;
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 60
; elefant_foot_compensation = 0.1
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 1
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 1
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 60
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #26A69A
; extruder_offset = 0x0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #26A69A
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.98
; filament_ids = GFL99
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 12
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Creality Generic PLA"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; filament start gcode\n"
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filename_format = {input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_target = nowhere
; gap_infill_speed = 200
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 1
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 7
; infill_wall_overlap = 25%
; inherits_group = "0.20mm Standard @Creality CR10SE 0.4";;
; initial_layer_acceleration = 1000
; initial_layer_infill_speed = 105
; initial_layer_jerk = 7
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 5000
; inner_wall_jerk = 7
; inner_wall_line_width = 0.45
; inner_wall_speed = 300
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 250
; ironing_angle = -1
; ironing_flow = 15%
; ironing_pattern = zig-zag
; ironing_spacing = 0.1
; ironing_speed = 44
; ironing_type = no ironing
; is_infill_first = 0
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0.42
; long_retractions_when_cut = 0
; machine_end_gcode = G91 ;Relative positioning \nG1 E-2 F2700 ;Retract a bit \nG1 E-2 Z0.2 F2400 ;Retract and raise Z \nG1 X5 Y5 F3000 ;Wipe out \nG1 Z3 ;Raise Z more \nG90 ;Absolute positioning \nG1 X2 Y218 F3000 ;Present print \nM106 S0 ;Turn-off fan \nM104 S0 ;Turn-off hotend \nM140 S0 ;Turn-off bed \nM84 X Y E ;Disable all steppers but Z
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 5000,5000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 8000,8000
; machine_max_acceleration_y = 8000,8000
; machine_max_acceleration_z = 500,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 2,2
; machine_max_speed_e = 100,100
; machine_max_speed_x = 600,600
; machine_max_speed_y = 600,600
; machine_max_speed_z = 30,30
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = M25
; machine_start_gcode = M220 S100 ;Reset feed rate \nM221 S100 ;Reset flow rate \n\nM140 S[bed_temperature_initial_layer_single] ;Set final bed temp\nG28 ;Home \nG92 E0 ;Reset extruder \nG1 Z2.0 F3000 ;Move Z Axis up \nG1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position \nM190 S[bed_temperature_initial_layer_single] ;Wait for bed temp to stabilize\nM109 S[nozzle_temperature_initial_layer] ;Wait for nozzle temp to stabilize\nG1 X10.1 Y145.0 Z0.28 F1500.0 E15 ;Draw the first line \nG1 X10.4 Y145.0 Z0.28 F5000.0 ;Move to side a little \nG1 X10.4 Y20 Z0.28 F1500.0 E30 ;Draw the second line \nG92 E0 ;Reset extruder \nG1 E-1.0000 F1800 ;Retract a bit \nG1 Z2.0 F3000 ;Move Z Axis up \nG1 E0.0000 F1800
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.32
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 10
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 220
; nozzle_temperature_initial_layer = 220
; nozzle_temperature_range_high = 230
; nozzle_temperature_range_low = 190
; nozzle_type = hardened_steel
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 5000
; outer_wall_jerk = 7
; outer_wall_line_width = 0.42
; outer_wall_speed = 250
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 35
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "Creality CR-10 SE 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @Creality CR10SE 0.4 - Copy
; printable_area = 0x0,220x0,220x220,0x220
; printable_height = 265
; printer_model = Creality CR-10 SE
; printer_notes = 
; printer_settings_id = Creality CR-10 SE 0.4 nozzle
; printer_structure = i3
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 50%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 2
; retraction_speed = 30
; role_based_wipe_speed = 1
; rotate_solid_infill_direction = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 2
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 8
; slow_down_layers = 0
; slow_down_min_speed = 10
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 20%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = crosshatch
; sparse_infill_speed = 300
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = -1
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.42
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 200
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.16
; support_type = normal(auto)
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 96x96/PNG, 300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 4
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 5000
; top_surface_jerk = 7
; top_surface_line_width = 0.42
; top_surface_pattern = monotonicline
; top_surface_speed = 250
; travel_acceleration = 5000
; travel_jerk = 7
; travel_slope = 3
; travel_speed = 400
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 40
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_double_wall = 3
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_loops = 2
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 0.000
; wipe_tower_x = 0
; wipe_tower_y = 250.000
; wipe_tower_y = 250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; z_offset = 0
; first_layer_bed_temperature = 60
; bed_shape = 0x0,220x0,220x220,0x220
; first_layer_temperature = 220
; first_layer_height = 0.200
; CONFIG_BLOCK_END


